name: auto_responsive_ui
description: "Smart responsive scaling engine for Flutter with adaptive layout support."
version: 0.0.3
homepage: https://github.com/vinov02/auto_responsive_ui.git

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
